config/routes.rb
MydomainNet::Application.routes.draw do

  get "password_resets/new"
  get "sessions/new"
  namespace :admin do
    resources :users
  end

  get "/(:sponsor)", to:  "users#index", as: :root, :constraints => { :sponsor => /[\w+\.]+/ }
  scope "/:sponsor", :constraints => { :sponsor => /[\w+\.]+/ } do

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    resources :users
    resources :sessions
    resources :password_resets

    resources :users
    resources :contacts
    namespace :office do
      resources :blogs
    end
  end

end

app/models/office.rb
module Office
  def self.table_name_prefix
    'office_'
  end
end

app/models/office/blog.rb
class Office::Blog < ActiveRecord::Base
end

app/controllers/office/blogs_controller.rb
class Office::BlogsController < ApplicationController
  before_action :set_office_blog, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /office/blogs
  # GET /office/blogs.json
  def index
    @office_blogs = Office::Blog.all
  end

  # GET /office/blogs/1
  # GET /office/blogs/1.json
  def show
  end

  # GET /office/blogs/new
  def new
    @office_blog = Office::Blog.new
  end

  # GET /office/blogs/1/edit
  def edit
  end

  # POST /office/blogs
  # POST /office/blogs.json
  def create
    @office_blog = Office::Blog.new(office_blog_params)

    respond_to do |format|
      if @office_blog.save
        format.html { redirect_to @office_blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @office_blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @office_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /office/blogs/1
  # PATCH/PUT /office/blogs/1.json
  def update
    respond_to do |format|
      if @office_blog.update(office_blog_params)
        format.html { redirect_to @office_blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @office_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /office/blogs/1
  # DELETE /office/blogs/1.json
  def destroy
    @office_blog.destroy
    respond_to do |format|
      format.html { redirect_to office_blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office_blog
      @office_blog = Office::Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_blog_params
      params.require(:office_blog).permit(:title)
    end
end

app/helpers/office/blogs_helper.rb
module Office::BlogsHelper
end

app/views/office/blogs/_form.html.erb
<%= form_for(@office_blog) do |f| %>
  <% if @office_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office_blog.errors.count, "error") %> prohibited this office_blog from being saved:</h2>

      <ul>
      <% @office_blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/office/blogs/edit.html.erb
<h1>Editing office_blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @office_blog %> |
<%= link_to 'Back', office_blogs_path %>

app/views/office/blogs/index.html.erb
<h1>Listing office_blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @office_blogs.each do |office_blog| %>
      <tr>
        <td><%= office_blog.title %></td>
        <td><%= link_to 'Show', office_blog %></td>
        <td><%= link_to 'Edit', edit_office_blog_path(office_blog) %></td>
        <td><%= link_to 'Destroy', office_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_office_blog_path %>

app/views/office/blogs/new.html.erb
<h1>New office_blog</h1>

<%= render 'form' %>

<%= link_to 'Back', office_blogs_path %>

app/views/office/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @office_blog.title %>
</p>

<%= link_to 'Edit', edit_office_blog_path(@office_blog) %> |
<%= link_to 'Back', office_blogs_path %>