config/routes.rb
MydomainNet::Application.routes.draw do

  get "password_resets/new"
  get "sessions/new"
  namespace :admin do
    resources :users
  end

  get "/(:sponsor)", to:  "users#index", as: :root, :constraints => { :sponsor => /[\w+\.]+/ }
  scope "/:sponsor", :constraints => { :sponsor => /[\w+\.]+/ } do

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    resources :users
    resources :sessions
    resources :password_resets

    resources :users
    resources :contacts
    namespace :office do
      resources :blogs
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MydomainNet</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="languages">
Language:
<%= link_to_unless_current "English", locale: "en" %> |
<%= link_to_unless_current "Portuguese", locale: "pt-BR" %> |
<%= link_to_unless_current "Español", locale: "es" %>
<h1><%= t "title" %></h1>
<em><%= t "description" %></em>
</div>


<div id="login">
  <% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
</div>


<%= yield %>

<div id="menu">
  <h1 id="">Links</h1>
  <ul>
    <li><%= link_to "Site Users", users_path %></li>
    <li><%= link_to "Admin Users", admin_users_path %></li>
    <li><%= link_to "Office Blogs", office_blogs_path %></li>
  </ul>
</div>

</body>
</html>
<%#= debug session %>
<%= debug flash %>
<%= debug params %>
<%= debug I18n.locale %>